kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - go get github.com/cloudflare/cloudflared/cmd/cloudflared
  - go build github.com/cloudflare/cloudflared/cmd/cloudflared
  - pwd
  # - tar -cf cloudflare-arm64.tar.gz /go/src/github.com/cloudflare/cloudflared/cmd/cloudflared/cloudflared

- name: publish
  image: plugins/github-release
  settings:
    api_key: 
      from_secret: GITHUB
    title: cloudflared-arm64
    # files: cloudflare-arm64.tar.gz
    files: github.com/cloudflare/cloudflared/cmd/cloudflared/cloudflared
  when:
    event: tag