kind: pipeline
name: arm64

trigger:
  event: [ tag ]
platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: golang:1.12.9-stretch
    commands:
      - go get github.com/cloudflare/cloudflared/cmd/cloudflared
      - go build github.com/cloudflare/cloudflared/cmd/cloudflared
      - cp /go/bin/cloudflared .
      - tar -cf cloudflared-arm64-${DRONE_COMMIT_MESSAGE}.tar.gz cloudflared

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB
      title: ${DRONE_COMMIT_MESSAGE}
      files: cloudflared-arm64-${DRONE_COMMIT_MESSAGE}.tar.gz
      
