kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - go get github.com/cloudflare/cloudflared/cmd/cloudflared
  - go build github.com/cloudflare/cloudflared/cmd/cloudflared
  # - cd /go/bin/ && tar -cf cloudflared-arm64.tar.gz cloudflared
  - cp /go/bin/cloudflared .

- name: publish
  image: plugins/github-release
  settings:
    api_key: 
      from_secret: GITHUB
    title: cloudflared-arm64
    # files: /go/bin/cloudflared-arm64.tar.gz
    files: cloudflared
  when:
    event: tag