kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: danacr
    password:
      from_secret: GITHUB
    repo: danacr/dashboard-metrics-scraper
    tags: arm64
